name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Start up Fuseki
      run: cd tests; sh ./init_fuseki.sh
    
    - name: Install Composer dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        php_extensions: gettext intl xsl

    - name: Run PHPUnit tests
      uses: osma/phpunit@v2-network-host-debug
      with:
        version: 8.5
        php_version: 7.4
        php_extensions: gettext intl xsl
