name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      fuseki:
        image: stain/jena-fuseki
        ports: 13030:3030

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Composer dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        php_extensions: gettext intl xsl

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v2
      with:
        version: 8.5
        php_version: 7.4
        php_extensions: gettext intl xsl
